from ..base import CRNBuildConfig


CONFIG = CRNBuildConfig(
    id='see_saw_pairwise_annihilation',
    multiplier='see_saw',
    rectifier='pairwise_annihilation',
    reporter='dual_act_reporter',
    status='source_derived_from_PWAnnTemp',
    description='Complete see-saw + pairwise-annihilation build template derived from the provided PWAnnTemp CRN.from_string structure.',
    crn_template='\n    PosInput + PosGateOutput -> PosInputGate + PosOutput; d11=1\n    PosInputGate + PosOutput -> PosInput + PosGateOutput; e11=1\n    PosInputGate + PosFuel -> PosInput + PosGateFuel; f11=1\n    PosInput + PosGateFuel -> PosInputGate + PosFuel; g11=1\n\n    PosOutput -> PosWeightedSum; p11=100\n\n    NegInput + NegGateOutput -> NegInputGate + NegOutput; h11=1\n    NegInputGate + NegOutput -> NegInput + NegGateOutput; i11=1\n    NegInputGate + NegFuel -> NegInput + NegGateFuel; j11=1\n    NegInput + NegGateFuel -> NegInputGate + NegFuel; o11=1\n\n    NegOutput -> NegWeightedSum; q11=100\n\n    PosWeightedSum + PWAnnihilator -> PosAnnihilator; a11=100\n    PosAnnihilator -> PosWeightedSum + PWAnnihilator; b11=100\n    PosAnnihilator + NegWeightedSum -> PosWaste + NegWaste; c11=100\n\n    PosWeightedSum + GateRestorer -> PosWeightedGate + FinalOutput; k11=1\n    PosWeightedGate + FinalOutput -> PosWeightedSum + GateRestorer; m11=1\n    PosWeightedGate + BFuel -> PosWeightedSum + PosWeightedFuel; l11=1\n    PosWeightedSum + PosWeightedFuel -> PosWeightedGate + BFuel; n11=1\n\n    NegWeightedSum + CGateRestorer -> NegWeightedGate + NegFinalOutput; v11=1\n    NegWeightedGate + NegFinalOutput -> NegWeightedSum + CGateRestorer; w11=1\n    NegWeightedGate + CFuel -> NegWeightedSum + NegWeightedFuel; s11=1\n    NegWeightedSum + NegWeightedFuel -> NegWeightedGate + CFuel; t11=1\n\n    FinalOutput + Reporter -> ActReporter; r11=1\n    NegFinalOutput + BReporter -> BActReporter; u11=1\n',
    species_template=['PosWeightedSum', 'PWAnnihilator', 'PosAnnihilator', 'NegWeightedSum', 'PosWaste', 'NegWaste', 'GateRestorer', 'PosWeightedGate', 'FinalOutput', 'BFuel', 'PosWeightedFuel', 'Reporter', 'ActReporter', 'PosInput', 'PosGateOutput', 'PosInputGate', 'PosOutput', 'PosFuel', 'PosGateFuel', 'NegInput', 'NegGateOutput', 'NegInputGate', 'NegOutput', 'NegFuel', 'NegGateFuel', 'CGateRestorer', 'NegWeightedGate', 'NegFinalOutput', 'CFuel', 'NegWeightedFuel', 'BReporter', 'BActReporter'],
    default_initial_conditions={'PWAnnihilator': 1.0, 'GateRestorer': 1.0, 'BFuel': 1.0, 'PosWeightedFuel': 1.0, 'Reporter': 1.0, 'ActReporter': 1.0, 'PosGateOutput': 1.0, 'PosFuel': 10.0, 'PosGateFuel': 1.0, 'NegGateOutput': 1.0, 'NegFuel': 10.0, 'NegGateFuel': 1.0, 'CGateRestorer': 1.0, 'CFuel': 1.0, 'NegWeightedFuel': 1.0, 'BReporter': 1.0, 'BActReporter': 1.0},
    role_map={'positive_input': 'PosInput', 'negative_input': 'NegInput', 'positive_weight': 'PosGateOutput', 'negative_weight': 'NegGateOutput', 'positive_weighted_sum': 'PosWeightedSum', 'negative_weighted_sum': 'NegWeightedSum', 'positive_reporter': 'ActReporter', 'negative_reporter': 'BActReporter', 'positive_fuel': 'PosFuel', 'negative_fuel': 'NegFuel', 'annihilator': 'PWAnnihilator', 'reporter': 'Reporter', 'negative_reporter_gate': 'BReporter', 'final_output': 'FinalOutput', 'negative_final_output': 'NegFinalOutput'},
)
