from ..base import CRNBuildConfig


CONFIG = CRNBuildConfig(
    id='see_saw_decoy',
    multiplier='see_saw',
    rectifier='decoy',
    reporter='dual_act_reporter',
    status='draft_template_unvalidated_chemistry',
    description='Buildable template-level CRN structure for see-saw multiplier with decoy rectifier. Replace/refine rates and reaction lines after motif-specific validation.',
    crn_template='\n    PosInput + PosGateOutput -> PosInputGate + PosOutput; ss_pos_bind=1\n    PosInputGate + PosOutput -> PosInput + PosGateOutput; ss_pos_unbind=1\n    PosInputGate + PosFuel -> PosInput + PosGateFuel; ss_pos_fuel=1\n    PosInput + PosGateFuel -> PosInputGate + PosFuel; ss_pos_restore=1\n    PosOutput -> PosWeightedSum; ss_pos_sum=100\n\n    NegInput + NegGateOutput -> NegInputGate + NegOutput; ss_neg_bind=1\n    NegInputGate + NegOutput -> NegInput + NegGateOutput; ss_neg_unbind=1\n    NegInputGate + NegFuel -> NegInput + NegGateFuel; ss_neg_fuel=1\n    NegInput + NegGateFuel -> NegInputGate + NegFuel; ss_neg_restore=1\n    NegOutput -> NegWeightedSum; ss_neg_sum=100\n\n\n    PosWeightedSum + Threshold -> PosInputThreshold + ActThresh; dec_pos_bind=10\n    PosInputThreshold + ActThresh -> PosWeightedSum + Threshold; dec_pos_reverse=0\n    PosWeightedSum + GateRestorer -> PosWeightedGate + FinalOutput; dec_pos_restore=1\n    PosWeightedGate + FinalOutput -> PosWeightedSum + GateRestorer; dec_pos_unrestore=1\n    PosWeightedGate + BFuel -> PosWeightedSum + PosWeightedFuel; dec_pos_fuel=1\n    PosWeightedSum + PosWeightedFuel -> PosWeightedGate + BFuel; dec_pos_refuel=1\n    FinalOutput + Reporter -> ActReporter; dec_report=1\n\n    NegWeightedSum + NegThreshold -> NegInputThreshold + NegActThresh; dec_neg_bind=10\n    NegInputThreshold + NegActThresh -> NegWeightedSum + NegThreshold; dec_neg_reverse=0\n    NegWeightedSum + CGateRestorer -> NegWeightedGate + NegFinalOutput; dec_neg_restore=1\n    NegFinalOutput + BReporter -> BActReporter; dec_neg_report=1\n',
    species_template=['PosInput', 'PosGateOutput', 'PosInputGate', 'PosOutput', 'PosFuel', 'PosGateFuel', 'PosWeightedSum', 'NegInput', 'NegGateOutput', 'NegInputGate', 'NegOutput', 'NegFuel', 'NegGateFuel', 'NegWeightedSum', 'Threshold', 'PosInputThreshold', 'ActThresh', 'GateRestorer', 'PosWeightedGate', 'FinalOutput', 'BFuel', 'PosWeightedFuel', 'Reporter', 'ActReporter', 'NegThreshold', 'NegInputThreshold', 'NegActThresh', 'CGateRestorer', 'NegWeightedGate', 'NegFinalOutput', 'BReporter', 'BActReporter'],
    default_initial_conditions={'PosGateOutput': 1.0, 'PosFuel': 10.0, 'PosGateFuel': 1.0, 'NegGateOutput': 1.0, 'NegFuel': 10.0, 'NegGateFuel': 1.0, 'Threshold': 1.0, 'PosInputThreshold': 1.0, 'GateRestorer': 1.0, 'BFuel': 1.0, 'PosWeightedFuel': 1.0, 'Reporter': 1.0, 'ActReporter': 1.0, 'NegThreshold': 1.0, 'NegInputThreshold': 1.0, 'CGateRestorer': 1.0, 'BReporter': 1.0, 'BActReporter': 1.0},
    role_map={'positive_input': 'PosInput', 'negative_input': 'NegInput', 'positive_weight': 'PosGateOutput', 'negative_weight': 'NegGateOutput', 'positive_weighted_sum': 'PosWeightedSum', 'negative_weighted_sum': 'NegWeightedSum', 'positive_reporter': 'ActReporter', 'negative_reporter': 'BActReporter', 'positive_fuel': 'PosFuel', 'negative_fuel': 'NegFuel', 'threshold': 'Threshold', 'negative_threshold': 'NegThreshold', 'reporter': 'Reporter', 'negative_reporter_gate': 'BReporter', 'final_output': 'FinalOutput', 'negative_final_output': 'NegFinalOutput'},
)
