from ..base import CRNBuildConfig


CONFIG = CRNBuildConfig(
    id='see_saw_weighted_subtraction',
    multiplier='see_saw',
    rectifier='weighted_subtraction',
    reporter='dual_act_reporter',
    status='draft_template_unvalidated_chemistry',
    description='Buildable template-level CRN structure for see-saw multiplier with weighted-subtraction rectifier. Replace/refine rates and reaction lines after motif-specific validation.',
    crn_template='\n    PosInput + PosGateOutput -> PosInputGate + PosOutput; ss_pos_bind=1\n    PosInputGate + PosOutput -> PosInput + PosGateOutput; ss_pos_unbind=1\n    PosInputGate + PosFuel -> PosInput + PosGateFuel; ss_pos_fuel=1\n    PosInput + PosGateFuel -> PosInputGate + PosFuel; ss_pos_restore=1\n    PosOutput -> PosWeightedSum; ss_pos_sum=100\n\n    NegInput + NegGateOutput -> NegInputGate + NegOutput; ss_neg_bind=1\n    NegInputGate + NegOutput -> NegInput + NegGateOutput; ss_neg_unbind=1\n    NegInputGate + NegFuel -> NegInput + NegGateFuel; ss_neg_fuel=1\n    NegInput + NegGateFuel -> NegInputGate + NegFuel; ss_neg_restore=1\n    NegOutput -> NegWeightedSum; ss_neg_sum=100\n\n\n    PosWeightedSum + NegWeightedSum -> SubtractionWaste; ws_annihilate=100\n    PosWeightedSum + GateRestorer -> PosWeightedGate + FinalOutput; ws_pos_restore=1\n    PosWeightedGate + FinalOutput -> PosWeightedSum + GateRestorer; ws_pos_reverse=1\n    PosWeightedGate + BFuel -> PosWeightedSum + PosWeightedFuel; ws_pos_fuel=1\n    PosWeightedSum + PosWeightedFuel -> PosWeightedGate + BFuel; ws_pos_refuel=1\n\n    NegWeightedSum + CGateRestorer -> NegWeightedGate + NegFinalOutput; ws_neg_restore=1\n    NegWeightedGate + NegFinalOutput -> NegWeightedSum + CGateRestorer; ws_neg_reverse=1\n    NegWeightedGate + CFuel -> NegWeightedSum + NegWeightedFuel; ws_neg_fuel=1\n    NegWeightedSum + NegWeightedFuel -> NegWeightedGate + CFuel; ws_neg_refuel=1\n\n    FinalOutput + Reporter -> ActReporter; ws_pos_report=1\n    NegFinalOutput + BReporter -> BActReporter; ws_neg_report=1\n',
    species_template=['PosInput', 'PosGateOutput', 'PosInputGate', 'PosOutput', 'PosFuel', 'PosGateFuel', 'PosWeightedSum', 'NegInput', 'NegGateOutput', 'NegInputGate', 'NegOutput', 'NegFuel', 'NegGateFuel', 'NegWeightedSum', 'SubtractionWaste', 'GateRestorer', 'PosWeightedGate', 'FinalOutput', 'BFuel', 'PosWeightedFuel', 'CGateRestorer', 'NegWeightedGate', 'NegFinalOutput', 'CFuel', 'NegWeightedFuel', 'Reporter', 'ActReporter', 'BReporter', 'BActReporter'],
    default_initial_conditions={'PosGateOutput': 1.0, 'PosFuel': 10.0, 'PosGateFuel': 1.0, 'NegGateOutput': 1.0, 'NegFuel': 10.0, 'NegGateFuel': 1.0, 'GateRestorer': 1.0, 'BFuel': 1.0, 'PosWeightedFuel': 1.0, 'CGateRestorer': 1.0, 'CFuel': 1.0, 'NegWeightedFuel': 1.0, 'Reporter': 1.0, 'ActReporter': 1.0, 'BReporter': 1.0, 'BActReporter': 1.0},
    role_map={'positive_input': 'PosInput', 'negative_input': 'NegInput', 'positive_weight': 'PosGateOutput', 'negative_weight': 'NegGateOutput', 'positive_weighted_sum': 'PosWeightedSum', 'negative_weighted_sum': 'NegWeightedSum', 'positive_reporter': 'ActReporter', 'negative_reporter': 'BActReporter', 'positive_fuel': 'PosFuel', 'negative_fuel': 'NegFuel', 'reporter': 'Reporter', 'negative_reporter_gate': 'BReporter', 'final_output': 'FinalOutput', 'negative_final_output': 'NegFinalOutput'},
)
