from ..base import CRNBuildConfig


CONFIG = CRNBuildConfig(
    id='switching_gate_weighted_subtraction',
    multiplier='switching_gate',
    rectifier='weighted_subtraction',
    reporter='dual_act_reporter',
    status='draft_template_unvalidated_chemistry',
    description='Buildable template-level CRN structure for switching-gate multiplier with weighted-subtraction rectifier. Replace/refine rates and reaction lines after motif-specific validation.',
    crn_template='\n    PosInput + PosGateOff -> PosGateOn; sw_pos_activate=1\n    PosGateOn + PosGateOutput -> PosGateOff + PosOutput; sw_pos_output=1\n    PosGateOn + PosFuel -> PosGateOff + PosGateFuel; sw_pos_fuel=1\n    PosOutput -> PosWeightedSum; sw_pos_sum=100\n\n    NegInput + NegGateOff -> NegGateOn; sw_neg_activate=1\n    NegGateOn + NegGateOutput -> NegGateOff + NegOutput; sw_neg_output=1\n    NegGateOn + NegFuel -> NegGateOff + NegGateFuel; sw_neg_fuel=1\n    NegOutput -> NegWeightedSum; sw_neg_sum=100\n\n\n    PosWeightedSum + NegWeightedSum -> SubtractionWaste; ws_annihilate=100\n    PosWeightedSum + GateRestorer -> PosWeightedGate + FinalOutput; ws_pos_restore=1\n    PosWeightedGate + FinalOutput -> PosWeightedSum + GateRestorer; ws_pos_reverse=1\n    PosWeightedGate + BFuel -> PosWeightedSum + PosWeightedFuel; ws_pos_fuel=1\n    PosWeightedSum + PosWeightedFuel -> PosWeightedGate + BFuel; ws_pos_refuel=1\n\n    NegWeightedSum + CGateRestorer -> NegWeightedGate + NegFinalOutput; ws_neg_restore=1\n    NegWeightedGate + NegFinalOutput -> NegWeightedSum + CGateRestorer; ws_neg_reverse=1\n    NegWeightedGate + CFuel -> NegWeightedSum + NegWeightedFuel; ws_neg_fuel=1\n    NegWeightedSum + NegWeightedFuel -> NegWeightedGate + CFuel; ws_neg_refuel=1\n\n    FinalOutput + Reporter -> ActReporter; ws_pos_report=1\n    NegFinalOutput + BReporter -> BActReporter; ws_neg_report=1\n',
    species_template=['PosInput', 'PosGateOff', 'PosGateOn', 'PosGateOutput', 'PosOutput', 'PosFuel', 'PosGateFuel', 'PosWeightedSum', 'NegInput', 'NegGateOff', 'NegGateOn', 'NegGateOutput', 'NegOutput', 'NegFuel', 'NegGateFuel', 'NegWeightedSum', 'SubtractionWaste', 'GateRestorer', 'PosWeightedGate', 'FinalOutput', 'BFuel', 'PosWeightedFuel', 'CGateRestorer', 'NegWeightedGate', 'NegFinalOutput', 'CFuel', 'NegWeightedFuel', 'Reporter', 'ActReporter', 'BReporter', 'BActReporter'],
    default_initial_conditions={'PosGateOff': 1.0, 'PosGateOutput': 1.0, 'PosFuel': 10.0, 'PosGateFuel': 1.0, 'NegGateOff': 1.0, 'NegGateOutput': 1.0, 'NegFuel': 10.0, 'NegGateFuel': 1.0, 'GateRestorer': 1.0, 'BFuel': 1.0, 'PosWeightedFuel': 1.0, 'CGateRestorer': 1.0, 'CFuel': 1.0, 'NegWeightedFuel': 1.0, 'Reporter': 1.0, 'ActReporter': 1.0, 'BReporter': 1.0, 'BActReporter': 1.0},
    role_map={'positive_input': 'PosInput', 'negative_input': 'NegInput', 'positive_weight': 'PosGateOutput', 'negative_weight': 'NegGateOutput', 'positive_weighted_sum': 'PosWeightedSum', 'negative_weighted_sum': 'NegWeightedSum', 'positive_reporter': 'ActReporter', 'negative_reporter': 'BActReporter', 'positive_fuel': 'PosFuel', 'negative_fuel': 'NegFuel', 'reporter': 'Reporter', 'negative_reporter_gate': 'BReporter', 'final_output': 'FinalOutput', 'negative_final_output': 'NegFinalOutput'},
)
