from ..base import CRNBuildConfig


CONFIG = CRNBuildConfig(
    id='toehold_exchange_pairwise_annihilation',
    multiplier='toehold_exchange',
    rectifier='pairwise_annihilation',
    reporter='dual_act_reporter',
    status='draft_template_unvalidated_chemistry',
    description='Buildable template-level CRN structure for toehold-exchange multiplier with pairwise-annihilation rectifier. Replace/refine rates and reaction lines after motif-specific validation.',
    crn_template='\n    PosInput + PosGateOutput -> PosInputGate; tex_pos_bind=1\n    PosInputGate + PosFuel -> PosInput + PosGateFuel + PosOutput; tex_pos_release=1\n    PosInputGate -> PosInput + PosGateOutput; tex_pos_unbind=0.1\n    PosOutput -> PosWeightedSum; tex_pos_sum=100\n\n    NegInput + NegGateOutput -> NegInputGate; tex_neg_bind=1\n    NegInputGate + NegFuel -> NegInput + NegGateFuel + NegOutput; tex_neg_release=1\n    NegInputGate -> NegInput + NegGateOutput; tex_neg_unbind=0.1\n    NegOutput -> NegWeightedSum; tex_neg_sum=100\n\n\n    PosWeightedSum + PWAnnihilator -> PosAnnihilator; pwa_pos_bind=100\n    PosAnnihilator -> PosWeightedSum + PWAnnihilator; pwa_pos_reverse=100\n    PosAnnihilator + NegWeightedSum -> PosWaste + NegWaste; pwa_annihilate=100\n\n    PosWeightedSum + GateRestorer -> PosWeightedGate + FinalOutput; pwa_pos_restore=1\n    PosWeightedGate + FinalOutput -> PosWeightedSum + GateRestorer; pwa_pos_reverse_gate=1\n    PosWeightedGate + BFuel -> PosWeightedSum + PosWeightedFuel; pwa_pos_fuel=1\n    PosWeightedSum + PosWeightedFuel -> PosWeightedGate + BFuel; pwa_pos_refuel=1\n\n    NegWeightedSum + CGateRestorer -> NegWeightedGate + NegFinalOutput; pwa_neg_restore=1\n    NegWeightedGate + NegFinalOutput -> NegWeightedSum + CGateRestorer; pwa_neg_reverse_gate=1\n    NegWeightedGate + CFuel -> NegWeightedSum + NegWeightedFuel; pwa_neg_fuel=1\n    NegWeightedSum + NegWeightedFuel -> NegWeightedGate + CFuel; pwa_neg_refuel=1\n\n    FinalOutput + Reporter -> ActReporter; pwa_pos_report=1\n    NegFinalOutput + BReporter -> BActReporter; pwa_neg_report=1\n',
    species_template=['PosInput', 'PosGateOutput', 'PosInputGate', 'PosFuel', 'PosGateFuel', 'PosOutput', 'PosWeightedSum', 'NegInput', 'NegGateOutput', 'NegInputGate', 'NegFuel', 'NegGateFuel', 'NegOutput', 'NegWeightedSum', 'PWAnnihilator', 'PosAnnihilator', 'PosWaste', 'NegWaste', 'GateRestorer', 'PosWeightedGate', 'FinalOutput', 'BFuel', 'PosWeightedFuel', 'CGateRestorer', 'NegWeightedGate', 'NegFinalOutput', 'CFuel', 'NegWeightedFuel', 'Reporter', 'ActReporter', 'BReporter', 'BActReporter'],
    default_initial_conditions={'PosGateOutput': 1.0, 'PosFuel': 10.0, 'PosGateFuel': 1.0, 'NegGateOutput': 1.0, 'NegFuel': 10.0, 'NegGateFuel': 1.0, 'PWAnnihilator': 1.0, 'GateRestorer': 1.0, 'BFuel': 1.0, 'PosWeightedFuel': 1.0, 'CGateRestorer': 1.0, 'CFuel': 1.0, 'NegWeightedFuel': 1.0, 'Reporter': 1.0, 'ActReporter': 1.0, 'BReporter': 1.0, 'BActReporter': 1.0},
    role_map={'positive_input': 'PosInput', 'negative_input': 'NegInput', 'positive_weight': 'PosGateOutput', 'negative_weight': 'NegGateOutput', 'positive_weighted_sum': 'PosWeightedSum', 'negative_weighted_sum': 'NegWeightedSum', 'positive_reporter': 'ActReporter', 'negative_reporter': 'BActReporter', 'positive_fuel': 'PosFuel', 'negative_fuel': 'NegFuel', 'annihilator': 'PWAnnihilator', 'reporter': 'Reporter', 'negative_reporter_gate': 'BReporter', 'final_output': 'FinalOutput', 'negative_final_output': 'NegFinalOutput'},
)
