from ..base import CRNBuildConfig


CONFIG = CRNBuildConfig(
    id='weight_loop_decoy',
    multiplier='weight_loop',
    rectifier='decoy',
    reporter='dual_act_reporter',
    status='draft_template_unvalidated_chemistry',
    description='Buildable template-level CRN structure for weight-loop multiplier with decoy rectifier. Replace/refine rates and reaction lines after motif-specific validation.',
    crn_template='\n    PosInput + PosLoopGate -> PosLoopComplex; wl_pos_bind=1\n    PosLoopComplex + PosGateOutput -> PosInput + PosLoopGate + PosOutput; wl_pos_output=1\n    PosLoopComplex + PosFuel -> PosInput + PosLoopFuel; wl_pos_fuel=1\n    PosLoopFuel -> PosLoopGate; wl_pos_reset=1\n    PosOutput -> PosWeightedSum; wl_pos_sum=100\n\n    NegInput + NegLoopGate -> NegLoopComplex; wl_neg_bind=1\n    NegLoopComplex + NegGateOutput -> NegInput + NegLoopGate + NegOutput; wl_neg_output=1\n    NegLoopComplex + NegFuel -> NegInput + NegLoopFuel; wl_neg_fuel=1\n    NegLoopFuel -> NegLoopGate; wl_neg_reset=1\n    NegOutput -> NegWeightedSum; wl_neg_sum=100\n\n\n    PosWeightedSum + Threshold -> PosInputThreshold + ActThresh; dec_pos_bind=10\n    PosInputThreshold + ActThresh -> PosWeightedSum + Threshold; dec_pos_reverse=0\n    PosWeightedSum + GateRestorer -> PosWeightedGate + FinalOutput; dec_pos_restore=1\n    PosWeightedGate + FinalOutput -> PosWeightedSum + GateRestorer; dec_pos_unrestore=1\n    PosWeightedGate + BFuel -> PosWeightedSum + PosWeightedFuel; dec_pos_fuel=1\n    PosWeightedSum + PosWeightedFuel -> PosWeightedGate + BFuel; dec_pos_refuel=1\n    FinalOutput + Reporter -> ActReporter; dec_report=1\n\n    NegWeightedSum + NegThreshold -> NegInputThreshold + NegActThresh; dec_neg_bind=10\n    NegInputThreshold + NegActThresh -> NegWeightedSum + NegThreshold; dec_neg_reverse=0\n    NegWeightedSum + CGateRestorer -> NegWeightedGate + NegFinalOutput; dec_neg_restore=1\n    NegFinalOutput + BReporter -> BActReporter; dec_neg_report=1\n',
    species_template=['PosInput', 'PosLoopGate', 'PosLoopComplex', 'PosGateOutput', 'PosOutput', 'PosFuel', 'PosLoopFuel', 'PosWeightedSum', 'NegInput', 'NegLoopGate', 'NegLoopComplex', 'NegGateOutput', 'NegOutput', 'NegFuel', 'NegLoopFuel', 'NegWeightedSum', 'Threshold', 'PosInputThreshold', 'ActThresh', 'GateRestorer', 'PosWeightedGate', 'FinalOutput', 'BFuel', 'PosWeightedFuel', 'Reporter', 'ActReporter', 'NegThreshold', 'NegInputThreshold', 'NegActThresh', 'CGateRestorer', 'NegWeightedGate', 'NegFinalOutput', 'BReporter', 'BActReporter'],
    default_initial_conditions={'PosLoopGate': 1.0, 'PosGateOutput': 1.0, 'PosFuel': 10.0, 'PosLoopFuel': 1.0, 'NegLoopGate': 1.0, 'NegGateOutput': 1.0, 'NegFuel': 10.0, 'NegLoopFuel': 1.0, 'Threshold': 1.0, 'PosInputThreshold': 1.0, 'GateRestorer': 1.0, 'BFuel': 1.0, 'PosWeightedFuel': 1.0, 'Reporter': 1.0, 'ActReporter': 1.0, 'NegThreshold': 1.0, 'NegInputThreshold': 1.0, 'CGateRestorer': 1.0, 'BReporter': 1.0, 'BActReporter': 1.0},
    role_map={'positive_input': 'PosInput', 'negative_input': 'NegInput', 'positive_weight': 'PosGateOutput', 'negative_weight': 'NegGateOutput', 'positive_weighted_sum': 'PosWeightedSum', 'negative_weighted_sum': 'NegWeightedSum', 'positive_reporter': 'ActReporter', 'negative_reporter': 'BActReporter', 'positive_fuel': 'PosFuel', 'negative_fuel': 'NegFuel', 'threshold': 'Threshold', 'negative_threshold': 'NegThreshold', 'reporter': 'Reporter', 'negative_reporter_gate': 'BReporter', 'final_output': 'FinalOutput', 'negative_final_output': 'NegFinalOutput'},
)
