from ..base import CRNBuildConfig


CONFIG = CRNBuildConfig(
    id='weight_race_weighted_subtraction',
    multiplier='weight_race',
    rectifier='weighted_subtraction',
    reporter='dual_act_reporter',
    status='draft_template_unvalidated_chemistry',
    description='Buildable template-level CRN structure for weight-race multiplier with weighted-subtraction rectifier. Replace/refine rates and reaction lines after motif-specific validation.',
    crn_template='\n    PosInput + PosRaceGate -> PosRaceComplex; wr_pos_bind=1\n    PosRaceComplex + PosGateOutput -> PosRaceGate + PosOutput; wr_pos_win=1\n    PosRaceComplex + PosFuel -> PosInput + PosRaceFuel; wr_pos_fuel=1\n    PosRaceFuel -> PosRaceGate; wr_pos_reset=1\n    PosOutput -> PosWeightedSum; wr_pos_sum=100\n\n    NegInput + NegRaceGate -> NegRaceComplex; wr_neg_bind=1\n    NegRaceComplex + NegGateOutput -> NegRaceGate + NegOutput; wr_neg_win=1\n    NegRaceComplex + NegFuel -> NegInput + NegRaceFuel; wr_neg_fuel=1\n    NegRaceFuel -> NegRaceGate; wr_neg_reset=1\n    NegOutput -> NegWeightedSum; wr_neg_sum=100\n\n\n    PosWeightedSum + NegWeightedSum -> SubtractionWaste; ws_annihilate=100\n    PosWeightedSum + GateRestorer -> PosWeightedGate + FinalOutput; ws_pos_restore=1\n    PosWeightedGate + FinalOutput -> PosWeightedSum + GateRestorer; ws_pos_reverse=1\n    PosWeightedGate + BFuel -> PosWeightedSum + PosWeightedFuel; ws_pos_fuel=1\n    PosWeightedSum + PosWeightedFuel -> PosWeightedGate + BFuel; ws_pos_refuel=1\n\n    NegWeightedSum + CGateRestorer -> NegWeightedGate + NegFinalOutput; ws_neg_restore=1\n    NegWeightedGate + NegFinalOutput -> NegWeightedSum + CGateRestorer; ws_neg_reverse=1\n    NegWeightedGate + CFuel -> NegWeightedSum + NegWeightedFuel; ws_neg_fuel=1\n    NegWeightedSum + NegWeightedFuel -> NegWeightedGate + CFuel; ws_neg_refuel=1\n\n    FinalOutput + Reporter -> ActReporter; ws_pos_report=1\n    NegFinalOutput + BReporter -> BActReporter; ws_neg_report=1\n',
    species_template=['PosInput', 'PosRaceGate', 'PosRaceComplex', 'PosGateOutput', 'PosOutput', 'PosFuel', 'PosRaceFuel', 'PosWeightedSum', 'NegInput', 'NegRaceGate', 'NegRaceComplex', 'NegGateOutput', 'NegOutput', 'NegFuel', 'NegRaceFuel', 'NegWeightedSum', 'SubtractionWaste', 'GateRestorer', 'PosWeightedGate', 'FinalOutput', 'BFuel', 'PosWeightedFuel', 'CGateRestorer', 'NegWeightedGate', 'NegFinalOutput', 'CFuel', 'NegWeightedFuel', 'Reporter', 'ActReporter', 'BReporter', 'BActReporter'],
    default_initial_conditions={'PosRaceGate': 1.0, 'PosGateOutput': 1.0, 'PosFuel': 10.0, 'PosRaceFuel': 1.0, 'NegRaceGate': 1.0, 'NegGateOutput': 1.0, 'NegFuel': 10.0, 'NegRaceFuel': 1.0, 'GateRestorer': 1.0, 'BFuel': 1.0, 'PosWeightedFuel': 1.0, 'CGateRestorer': 1.0, 'CFuel': 1.0, 'NegWeightedFuel': 1.0, 'Reporter': 1.0, 'ActReporter': 1.0, 'BReporter': 1.0, 'BActReporter': 1.0},
    role_map={'positive_input': 'PosInput', 'negative_input': 'NegInput', 'positive_weight': 'PosGateOutput', 'negative_weight': 'NegGateOutput', 'positive_weighted_sum': 'PosWeightedSum', 'negative_weighted_sum': 'NegWeightedSum', 'positive_reporter': 'ActReporter', 'negative_reporter': 'BActReporter', 'positive_fuel': 'PosFuel', 'negative_fuel': 'NegFuel', 'reporter': 'Reporter', 'negative_reporter_gate': 'BReporter', 'final_output': 'FinalOutput', 'negative_final_output': 'NegFinalOutput'},
)
