from ..base import CRNBuildConfig


CONFIG = CRNBuildConfig(
    id='weight_race_decoy',
    multiplier='weight_race',
    rectifier='decoy',
    reporter='dual_act_reporter',
    status='draft_template_unvalidated_chemistry',
    description='Buildable template-level CRN structure for weight-race multiplier with decoy rectifier. Replace/refine rates and reaction lines after motif-specific validation.',
    crn_template='\n    PosInput + PosRaceGate -> PosRaceComplex; wr_pos_bind=1\n    PosRaceComplex + PosGateOutput -> PosRaceGate + PosOutput; wr_pos_win=1\n    PosRaceComplex + PosFuel -> PosInput + PosRaceFuel; wr_pos_fuel=1\n    PosRaceFuel -> PosRaceGate; wr_pos_reset=1\n    PosOutput -> PosWeightedSum; wr_pos_sum=100\n\n    NegInput + NegRaceGate -> NegRaceComplex; wr_neg_bind=1\n    NegRaceComplex + NegGateOutput -> NegRaceGate + NegOutput; wr_neg_win=1\n    NegRaceComplex + NegFuel -> NegInput + NegRaceFuel; wr_neg_fuel=1\n    NegRaceFuel -> NegRaceGate; wr_neg_reset=1\n    NegOutput -> NegWeightedSum; wr_neg_sum=100\n\n\n    PosWeightedSum + Threshold -> PosInputThreshold + ActThresh; dec_pos_bind=10\n    PosInputThreshold + ActThresh -> PosWeightedSum + Threshold; dec_pos_reverse=0\n    PosWeightedSum + GateRestorer -> PosWeightedGate + FinalOutput; dec_pos_restore=1\n    PosWeightedGate + FinalOutput -> PosWeightedSum + GateRestorer; dec_pos_unrestore=1\n    PosWeightedGate + BFuel -> PosWeightedSum + PosWeightedFuel; dec_pos_fuel=1\n    PosWeightedSum + PosWeightedFuel -> PosWeightedGate + BFuel; dec_pos_refuel=1\n    FinalOutput + Reporter -> ActReporter; dec_report=1\n\n    NegWeightedSum + NegThreshold -> NegInputThreshold + NegActThresh; dec_neg_bind=10\n    NegInputThreshold + NegActThresh -> NegWeightedSum + NegThreshold; dec_neg_reverse=0\n    NegWeightedSum + CGateRestorer -> NegWeightedGate + NegFinalOutput; dec_neg_restore=1\n    NegFinalOutput + BReporter -> BActReporter; dec_neg_report=1\n',
    species_template=['PosInput', 'PosRaceGate', 'PosRaceComplex', 'PosGateOutput', 'PosOutput', 'PosFuel', 'PosRaceFuel', 'PosWeightedSum', 'NegInput', 'NegRaceGate', 'NegRaceComplex', 'NegGateOutput', 'NegOutput', 'NegFuel', 'NegRaceFuel', 'NegWeightedSum', 'Threshold', 'PosInputThreshold', 'ActThresh', 'GateRestorer', 'PosWeightedGate', 'FinalOutput', 'BFuel', 'PosWeightedFuel', 'Reporter', 'ActReporter', 'NegThreshold', 'NegInputThreshold', 'NegActThresh', 'CGateRestorer', 'NegWeightedGate', 'NegFinalOutput', 'BReporter', 'BActReporter'],
    default_initial_conditions={'PosRaceGate': 1.0, 'PosGateOutput': 1.0, 'PosFuel': 10.0, 'PosRaceFuel': 1.0, 'NegRaceGate': 1.0, 'NegGateOutput': 1.0, 'NegFuel': 10.0, 'NegRaceFuel': 1.0, 'Threshold': 1.0, 'PosInputThreshold': 1.0, 'GateRestorer': 1.0, 'BFuel': 1.0, 'PosWeightedFuel': 1.0, 'Reporter': 1.0, 'ActReporter': 1.0, 'NegThreshold': 1.0, 'NegInputThreshold': 1.0, 'CGateRestorer': 1.0, 'BReporter': 1.0, 'BActReporter': 1.0},
    role_map={'positive_input': 'PosInput', 'negative_input': 'NegInput', 'positive_weight': 'PosGateOutput', 'negative_weight': 'NegGateOutput', 'positive_weighted_sum': 'PosWeightedSum', 'negative_weighted_sum': 'NegWeightedSum', 'positive_reporter': 'ActReporter', 'negative_reporter': 'BActReporter', 'positive_fuel': 'PosFuel', 'negative_fuel': 'NegFuel', 'threshold': 'Threshold', 'negative_threshold': 'NegThreshold', 'reporter': 'Reporter', 'negative_reporter_gate': 'BReporter', 'final_output': 'FinalOutput', 'negative_final_output': 'NegFinalOutput'},
)
